### ISSUE TITLE
Merge into `manta-js`

### ISSUE THREAD

**Issue by bhgomes** [Manta-Network/Dev-Tools#1]
@gabcbrown Should this be merged into [`manta-js`](https://github.com/Manta-Network/manta-js) and/or [`manta-dev-cli`](https://github.com/Manta-Network/manta-dev-cli)?

**Comment by gabcbrown** [comment]
Yes, there are a couple of repositories that I opened in the process of experimenting on what ultimately became `manta-js`. I'll merge in anything that's left and clean them up. Thanks!

**Comment by bhgomes** [comment]
This will eventually be moved to https://github.com/manta-network/cli
